### ISSUE TITLE
Identify Enpoint Pagination

### ISSUE THREAD

**Issue by firepenguindisopanda** [uwidcit/myAdvisorDev#79]
# Identify Which Backend Endpoints Would Need Pagination

### Task: Review existing backend endpoints and identify where pagination is necessary.

**Diagram Work**:
*Create or Adjust (if previously created)*

- Use Case Diagram: Create use case diagram to show which endpoints involve pagination.
- Sequence Diagram: Create a sequence diagram to illustrate how the backend handles paginated requests.
- Flowchart: Map out a flowchart showing the decision process for implementing pagination.

**Comment by uni-paul-taylor2** [comment]
https://github.com/uwidcit/myAdvisorDev/pull/81

**Comment by uni-paul-taylor2** [comment]
https://github.com/uwidcit/myAdvisorDev/pull/82

**Comment by firepenguindisopanda** [comment]
> Please provide a document identifying the endpoints that need pagination

**Comment by uni-paul-taylor2** [comment]
Will give document today

**Comment by uni-paul-taylor2** [comment]
In the routes folder, there were 3 files that had routes that implied the need of pagination. These files were `courses.js`. `programmes.js` and `semester.js`. The routes to paginate are:
- **GET** `/courses/all`
- **GET** `/courses/departments`
- **GET** `/programmes/all`
- **GET** `/semester/all`

#### Side note
However at the time of writing this report, a direct search of the term "paginate" also existed before this task in areas before I was contributing to this project. These files are `admin.js` and `student.js` and their pagination technique uses query parameters _page_ and _itemsPerPage_ where _page_ is the page number and _itemsPerPage_ represents. Since the code existed before, although it is different from my current method of pagination, it will not be hard to switch the new paginated routes to the stated logic or to switch these old paginated routes from its logic to the new logic. The new method/logic is using request headers instead of query parameters, these request headers are where the `page_number` header would be equivalent to the _page_ query parameter and the `page_size` header would be equivalent to the _itemsPerPage_ query parameter. The preexisting paginated routes using the old logic are below.
- **GET** `/admin/course-plan/all/:semesterId/:page/:itemsPerPage`
- **GET** `/student/course-plans/:semesterId`

**Comment by firepenguindisopanda** [comment]
I think it's best to use the method in the preexisting paginated routes @uni-paul-taylor2
